### ISSUE TITLE
Duda sobre implementación del programa y un error en el Test.

### ISSUE THREAD

**Issue by VlatkoMarchanSekulic** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct09-filesystem-notes-app-alu0101321141#1]
Hola, buenos días.

Mi duda viene sobre la implementación del programa, ya que lo he implementado utilizando una clase gestor de notas la cual trabaja sobre los ficheros creando la carpeta del usuario y guardando en JSON  las notas. Mi duda viene en si es necesario crear una _clase usario_ para ir guardando las notas del usuario en una lista (array). 

A priori no implementé la _clase usuario_ ya que trabajando con los ficheros puedo manejar directamente la información haciéndola persistente y me pareció innecesaria la creación de dicha clase. Pero no se si de esa manera cumplo con el enunciado en este aspecto:

> Cada usuario tendrá su propia lista de notas,

Por otro lado, al realizar el push y ser analizado el código me falló el test build (12.x) y no se como solucionar el error. (Solucionado, el error venía porque la función _rmSync()_ no existía en esa versión de node)

Un saludo y gracias de antemano.

**Comment by esegredo** [comment]
Hola, buenas tardes.

Efectivamente, no hace falta crear una clase usuario dado que simplemente debe ser un argumento pasado desde la línea de comandos para saber en qué directorio se almacenan las notas de dicho usuario.

Saludos.

**Comment by VlatkoMarchanSekulic** [comment]
Perfecto, muchas gracias.
